In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
raw_csv_data = np.loadtxt('1.1 Audiobooks_data.csv.csv',delimiter=',')

unscaled_input_all = raw_csv_data[:,1:-1]


#array = [0,1,2,3,4,5,6,7,8,9]

array([1.404e+03, 2.808e+03, 6.660e+00, 1.333e+01, 1.000e+00, 6.500e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.820e+02])

In [4]:
ar = array[:1:-1]

In [6]:
print(ar)

[9, 8, 7, 6, 5, 4, 3, 2]


In [9]:
raw_csv_data[1]

array([6.110e+02, 1.404e+03, 2.808e+03, 6.660e+00, 1.333e+01, 1.000e+00,
       6.500e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.820e+02, 1.000e+00])

In [17]:
ar2=array[:1:-1]
ar2

[9, 8, 7, 6, 5, 4, 3, 2]

In [51]:
print(raw_csv_data[0][1])
unscaled_input_all.shape

2160.0


(14084, 10)

In [4]:
for i in range(0,12):
    print(raw_csv_data[0][i])

873.0
2160.0
2160.0
10.13
10.13
0.0
8.91
0.0
0.0
0.0
0.0
1.0


In [5]:
for i in range(0,12):
    print(unscaled_input_all[0][i])

2160.0
2160.0
10.13
10.13
0.0
8.91
0.0
0.0
0.0
0.0


IndexError: index 10 is out of bounds for axis 0 with size 10

In [44]:
arrr

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [45]:
arrr[:1:-1]  

array([[4, 4, 4],
       [3, 3, 3],
       [2, 2, 2]])

In [6]:
 target_all = raw_csv_data[:,-1]

In [7]:
target_all.shape

(14084,)

In [8]:
target_all[0]

1.0

In [36]:
num_one_targets = int(np.sum(target_all))
zero_targets_counter = 0
indices_to_remove = []

for i in range(target_all.shape[0]):
    if target_all[i] == 0:
        zero_targets_counter += 1
        if zero_targets_counter > num_one_targets:
            indices_to_remove.append(i)
        
unscaled_inputs_equal_priors = np.delete(unscaled_input_all,indices_to_remove,axis=0)
targets_equal_priors = np.delete(target_all,indices_to_remove,axis=0)

In [37]:
unscaled_input_all.shape

(14084, 10)

In [38]:
unscaled_inputs_equal_priors.shape

(4474, 10)

In [18]:
target_all.shape[0]

14084

In [19]:
np.sum(target_all)

2237.0

In [24]:
indices_to_remove = []

In [25]:
indices_to_remove.append(1)

In [26]:
indices_to_remove.append(2)

In [27]:
indices_to_remove

[1, 2]

In [41]:
print(indices_to_remove[1])

4475


SCALEING THE INPUT

In [39]:
scaled_inputs = preprocessing.scale(unscaled_inputs_equal_priors)

In [44]:
scaled_inputs.shape

(4474, 10)

Shuffling the data

In [69]:
shuffled_indices = np.arange(scaled_inputs.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = scaled_inputs[shuffled_indices]
shuffled_targets = targets_equal_priors[shuffled_indices]

In [62]:
aa = np.array([[0,9,9],[1,1,1],[3,3,3]])

In [63]:
aa.shape

(3, 3)

In [64]:
aa.shape[0]

3

In [65]:
a = np.arange(aa.shape[0])

In [77]:
sample_counts = shuffled_inputs.shape[0]

train_samples_count = int(0.8*sample_counts)
validation_samples_count = int(0.1*sample_counts)
test_sample_count = sample_counts - train_samples_count - validation_samples_count

train_inputs = shuffled_inputs[:train_samples_count]
train_targets = shuffled_targets[:train_samples_count]

validation_input = shuffled_inputs[train_samples_count:train_samples_count + validation_samples_count]
validation_targets = shuffled_targets[train_samples_count :train_samples_count +validation_samples_count]

test_inputs = shuffled_inputs[train_samples_count +validation_samples_count: train_samples_count +validation_samples_count +test_sample_count]
test_targets = shuffled_targets[train_samples_count +validation_samples_count:]



In [82]:
print(np.sum(train_targets)/ train_samples_count)
print(np.sum(validation_targets)/ validation_samples_count)
print(np.sum(test_targets)/ test_sample_count)

0.4979044425817267
0.4809843400447427
0.5357142857142857


In [99]:
print(np.sum(train_targets))
print(np.sum(validation_targets))
print(np.sum(test_targets))

1782.0
215.0
240.0


In [88]:
train_inputs.shape[0]

3579

In [87]:
train_targets.shape

(3579,)

In [90]:
np.sum(train_inputs.shape[0])

3579

In [91]:
np.sum(train_targets.shape)

3579

In [92]:
np.sum(train_targets)

1782.0

In [94]:
np.sum(train_inputs[0])

15.473552981025561

In [97]:
train_targets[2]

0.0

SAVEIN THE DATASET IN NPZ FORMAT

In [103]:
np.savez('train_dataset', inputs = train_inputs, targets = train_targets)
np.savez('validation_dataset', inputs = validation_input, targets = validation_targets)
np.savez('test_dataset', inputs = test_inputs, targets = test_targets)